### PR TITLE
new platforms osx386 and osxppc

### PR DESCRIPTION
**Pull request by kernigh**
This adds platforms for Mac OS X for both Intel and PowerPC. I add osx386 and osxppc to the top build.lua, and provide plat/osx*/README files, but I don't update the top README. As usual, the platforms can't link to libraries from other compilers, and the libsys provides only a small set of system calls.

The new **cvmach** utility converts ack.out files to Mach-o format for Mac OS X. Each executable has an RX segment, an RW segment, and a symbol table. So osx386 and osxppc become the only platforms to preserve the symbol table in the executable. (Our aelflod for Linux emits ELF files without a symbol table.)

I provide a manual page for cvmach(6) but don't install it. I wrote it with the new mdoc(7) macros, not the traditional man(7) macros. All other manual pages use man(7).

The pull request includes commit 88c2ea6 to use uint32_t in util/led/main.c. I experimented with a new led option while testing cvmach. I didn't commit the new option, but I left in the uint32_t change. The pull request also includes 19310d2 to allow #include <object.h>. So far, cvmach is the only program to include it. Other programs use the library without the header.

I have oddly arranged the dependencies in the build system.
- Each of plat/osx386+tools and plat/osxppc+tools have a dependency on plat/osx/cvmach+pkg, because without the dependency, **cvmach** would never be built. This is odd, because the libraries in plat/osx386+pkg and plat/osxppc+pkg depend on cvmach, but we don't use cvmach to build the libraries. The libraries don't depend on led, so `gmake MAKECMDGOALS="plat/osxppc+pkg"` installs the compiler, its libraries, and cvmach, but not led. We need `gmake MAKECMDGOALS="plat/osxppc+pkg util/led+pkg"` to produce osxppc executables.
- Each OS X platform shares **as** and **ncg** with a Linux platform, because I don't want to waste time building another as or ncg for OS X. The descr for osxppc calls as, ncg, and **top** in the linuxppc directory. In the build system, plat/osxppc+tools depends on plat/linuxppc+tools. This causes osxppc to uselessly depend on the descr for linuxppc and on aelflod. There's no target that would install as, ncg, and top, without installing the Linux stuff.
- The two OS X platforms share the headers in plat/osx/include, and their descr files have instructions to use the single installed copy of those headers. This differs from our three Linux platforms, which have three copies of the header files. The build system has dependencies on plat/osx386/include+headers on plat/osxppc/include+headers, so I provide them as phony targets that depend on the real headers in plat/osx/include+headers.

The osxppc platform passes my tests in [1271b03 of ack-ptest](https://bitbucket.org/kernigh/ack-ptest/commits/1271b031a63e9897c70f389dda02430d1aa779ea). My test harness does ssh to a PowerPC Mac. This pull request has no tests for osx386 nor osxppc because the ack's own test harness does not ssh to another machine.

Most programs from examples/ seem to work on both osx386 and osxppc. Beware that hilo.mod does not work on osxppc or linuxppc (issue #22). Also, hilo.b does not work on any platform that I have tried.

### CODE REVIEW

**Comment by kernigh** [comment]
After I made this pull request, Travis found a problem.

```
lang/basic/lib+lib_osxppc/trap
"/tmp/ack-build/obj/lang/cem/libcc.ansi/headers/headers/signal.h", line 13: cannot open include file "unistd.h"
...
"lang/basic/lib/trap.c", line 43: _NSIG undefined
"lang/basic/lib/trap.c", line 44: (warning) implicit declaration of function signal
...
make[1]: *** [lang/basic/lib+lib_osxppc/trap-IMPL] Error 1
```

Something is wrong with my dependencies in the build system. The build isn't finding plat/osx/include/unistd.h.

I can build 969e98b on my OpenBSD machine if I disable the tests to work around issue #19. (I hadn't merged the fix for that issue.) But I used ninja and Travis used make.

**Comment by davidgiven** [comment]
The dependency issue is because the rules in plat/osx{ppc,386}/include/build.lua was depending on plat/osx/include+headers, but didn't actually have any outputs. The  basic standard libraries depended on plat/$PLAT/include+headers in order to get the platform headers on their include paths, so this meant that no paths were added.

It was working with ninja (and with gmake in parallel mode) because they happened to be building plat/$PLAT/include+pkg before tackling the language libraries, which meant the headers were getting copied into the staging directory and found via the path in the descr. But that was a race.

I've merged your PR into this branch and applied some fixes: https://github.com/davidgiven/ack/tree/kernigh-pr-osx

...

Re the tools: depending on cvmach from +tools is correct; +tools is supposed to contain stuff that's needed to build the plat but doesn't actually run the ACK (to avoid dependency loops). led is depended on by the ackprogram rule itself, so that internal builds get it automatically; but it's exposed to the end user via the top-level rules in build.lua. (That all probably needs a refactor to allow individual plats to be built one at a time.)

Re sharing as, ncg, mcg, top: I'd rather not do this (yet). As you've found out, it makes the dependencies muddled, and they're hard enough to get right as it is. Originally it was like this because each tool could be built with different compilation flags to enable or disable various features, but that doesn't happen any more. One day it'd be worthwhile to refactor all of this to keep the various tools in common, but as they're tiny (ncg for 386 is 100k), I don't think it's worth the extra build complexity.

Re sharing the headers: beware! The Linux headers for each plat are *different*, which is why they're split up like that. But if OSX doesn't need to do that, having a common directory is fine.

**Comment by kernigh** [comment]
Added the fixes from @davidgiven, and one more commit to stop sharing as, ncg, top between Linux and OS X.

While testing this, I found another race in the build system. It seems that hilo.b doesn't depend on the Basic compiler. I had built targets plat/osx386+pkg, plat/osxppc+pkg, util/led, to check that I can build them without installing linux386 and linuxppc tools. When I did gmake to build everything else, I got errors about can't execute em_bem. I finished the build by repeating gmake until it succeeded.

**Comment by davidgiven** [comment]
Re the race: yup. Filed another #4.

**Comment by davidgiven** [comment]
Merged. Thank you very much for the work!

**Pull request merged**
