### PR TITLE
First pull request

### PR DESCRIPTION
**Pull request by ccodere**
This is my first pull request, started from a newly created fork of your repository:
I am manually merging everything, and as discussed by email, i am doing it part by part.
Main changes that could potentially be impacting in this pull request:
* LLGen now generates ANSI C code by default.
* I built those utilities on my side and they seem to work with some manual tests.

One issue is that some file are using windows line endings, hope its not too big of an issue, next file that I will modify should be ok.

Other pull requests coming...The issue is that some libraries that I already made ANSI compatible such as em_code / libsystem / objects, it will impact everything, so i need to move forward much more before i can do big pull requests.

### CODE REVIEW

**Comment by davidgiven** [comment]
It looks like the cmake changes have broken the ninja build --- see the CI results above (Travis is the Linux build, Appveyor is cygwin).

Can I ask you to move the cmake stuff to a different branch? I don't want to merge that until I can see that building the code generators and libraries work. The front end compilers are easy, because they only need to be built once...

**Comment by ccodere** [comment]
I just saw that, you are right... i just tested it on my part with both ninja and standard make, and I do get the same issue as you, it chokes, i will fix this, not sure where it comes from. OTOH the default branch is supposed to build on MacOS or not? I wanted to compare and from the original clone, but it stops on .../em_data/new_table...

**Comment by ccodere** [comment]
Really sorry ,I discovered the issue, it was in LLgen, by trying to make it ANSI C, I broke something. On the other hand, I am not able to fully build the original code on my Mac that I just cloned from the default here without any of my modifications... I want to make sure that my next pull request builds using both ninja and make using your build scripts and CMake... Since it seems CLang is pickier than gcc, i will need to fix other things first so its builds properly.

I am ok to create a branch, but i don't think i have write access to create it... you need to tell me where they should go into then.

**Comment by ccodere** [comment]
Let me retry by using a branch....

**Comment by davidgiven** [comment]
Sorry, I was getting the OSX working again... if you merge from trunk, you should just be able to do 'make' in the root directory and have it work.

I'd suggest creating some new branches in your own repository, making sure it's up-to-date from mine, and then cherrypicking the individual commits above into them. Then when you push to github it should automatically run the builds. (Or just copy the files and do a new commit, which is what you did above, I think?)

The goal is to try and split things up into small, self-contained changes which can be easily tested.

**Pull request closed without merging**
