### PR TITLE
better code from PowerPC ncg and mcg

### PR DESCRIPTION
**Pull request by kernigh**
With these changes, PowerPC ncg understands more EM instructions and emits better code, and PowerPC mcg passes the tests. There is a problem: I am seeing smoke from Travis. I enabled Travis for kernigh/ack and [saw this error](https://travis-ci.org/kernigh/ack/jobs/351096452):

```
examples+startrek_c_linuxppc/main/startrek
*** Error in `/tmp/ack-build/staging/lib/ack/ego/cs': free(): invalid pointer: 0x0000000001c078e0 ***
ego: /tmp/ack-build/staging/lib/ack/ego/cs got a unix signal
make[1]: *** [examples+startrek_c_linuxppc/main/startrek-IMPL] Error 1
```

I can't reproduce this error outside Travis, so I don't know the cause and have no fix. My OpenBSD/amd64 machine can build this branch, and PowerPC Linux can build commit 0720671 (disabling all plats but linuxppc).

- I added more tests for C, Modula-2, and EM, including setjmp() in C, Semaphores in Modula-2, and weird EM instructions like `dus` and `rol`.
- I taught PowerPC ncg to pass these tests.
- I added some missing pieces like `.fef4` to libem. I also provided a shorter `.cfu8`.
- I made some fixes for i80 and i86 (34cf0c8, c95bcac, a1d1f38).
- I got mcg far enough to pass everything in tests/plat. I abused IR_SETRET so mcg would work with libem; see helper_function_with_arg() in mach/proto/mcg/treebuilder.c. There are still problems with mcg. The code to preserve registers like r31 across function calls doesn't look right. The `mes 11` for `gto` isn't handled. The floating-point probably doesn't work.
- I improved the code from ncg. It now has a better chance to put values in the correct register without an extra move. Coercions do `uses REG=%1` instead of `uses REG move %1, %a` (d8fa9d1). I added FRAME_V tokens to try to kill fewer tokens during store. The code started using `subfic` and `mulli`.
- I added some optimizations to top, the target optimizer. It tries to remove `mr. X, X` instructions (5f2a7b2). It tries to merge or delete `addi sp, sp, UP` instructions (b90c97b).
- I revised sigaction() for linuxppc because a signal handler might call sigaction() (103d44c).
- I taught ego/cs to optimize procedures that do both division `a / b` and remainder `a % b`, but I enabled this only for PowerPC (b1b737e).
- I added instructions like `lwarx` to the PowerPC assembler (b1badf1).
- There are a bunch of smaller changes.

### CODE REVIEW

**Comment by davidgiven** [comment]
I can duplicate the crash on my Linux system --- I've tried with both ARM and amd64. It's a multiple free:

```
==2715== Invalid read of size 8
==2715==    at 0x10A2E1: okay_lines (cs_profit.c:194)
==2715==    by 0x10A2E1: desirable (cs_profit.c:223)
==2715==    by 0x1091B5: eliminate (cs_elim.c:312)
==2715==    by 0x108C28: cs_optimize (cs.c:72)
==2715==    by 0x10B6EF: go (go.c:127)
==2715==    by 0x108C95: main (cs.c:80)
==2715==  Address 0x529ab40 is 0 bytes inside a block of size 32 free'd
==2715==    at 0x4C2DDBB: free (vg_replace_malloc.c:530)
==2715==    by 0x10CDCD: oldline (alloc.c:129)
==2715==    by 0x10948A: remove_lines (cs_elim.c:43)
==2715==    by 0x10948A: replace (cs_elim.c:180)
==2715==    by 0x10948A: set_replace (cs_elim.c:245)
==2715==    by 0x10948A: eliminate (cs_elim.c:325)
==2715==    by 0x108C28: cs_optimize (cs.c:72)
==2715==    by 0x10B6EF: go (go.c:127)
==2715==    by 0x108C95: main (cs.c:80)
==2715==  Block was alloc'd at
==2715==    at 0x4C2EBA5: calloc (vg_replace_malloc.c:711)
==2715==    by 0x10CE74: myalloc (alloc.c:237)
==2715==    by 0x10CEAB: newline (alloc.c:119)
==2715==    by 0x10C0A3: read_line (get.c:373)
==2715==    by 0x10C35A: getlines (get.c:462)
==2715==    by 0x10C4CD: getunit (get.c:516)
==2715==    by 0x10B6CC: go (go.c:112)
==2715==    by 0x108C95: main (cs.c:80)
```

The version of cs in head doesn't crash like this... unless I try it on one of the data files from your branch. Assuming they're compatible then it's entirely possible this is a preexisting bug which is being provoked by some of your new ego rules. (Trying your cs against data files from head doesn't crash either.)

I'm attaching the valgrind log. 

[valgrind.log](https://github.com/davidgiven/ack/files/1798411/valgrind.log)

**Comment by kernigh** [comment]
Thank you for the valgrind.log; I now see where ego/cs is misbehaving by reading from `struct line`s after freeing them. This gives me another chance to fix the problem.

I can now also reproduce this in OpenBSD/amd64:

```
$ gmake clean
...
$ MALLOC_OPTIONS=j gmake
...
[4029/5677] ACKDIR=/home/kernigh/park/...les/startrek_c_linuxppc/platstamp -O6 
FAILED: /home/kernigh/park/ack-build/obj/examples/startrek_c_linuxppc/main/startrek/startrek.o 
ACKDIR=/home/kernigh/park/ack-build/staging /home/kernigh/park/ack-build/staging/bin/ack -mlinuxppc -c -o /home/kernigh/park/ack-build/obj/examples/startrek_c_linuxppc/main/startrek/startrek.o examples/startrek.c -I/home/kernigh/park/ack-build/obj/examples/startrek_c_linuxppc/platstamp -O6 
cs(47469) in free(): chunk is already free 0xdb74f65e020
ego: /home/kernigh/park/ack-build/staging/lib/ack/ego/cs got a unix signal
```

So `MALLOC_OPTIONS=j` turns off "junk" in OpenBSD's malloc. By default, free() overwrites smaller allocations with some junk. I usually want junk, because if a program reads the junk, it will probably crash or give bad output.

But here, the junk hides the problem. Without the junk, I see the double free. With the junk, CS seems to avoid the double free and emit a correctly optimized program.

**Comment by davidgiven** [comment]
Is there a way to change the junk value? Could we just being unlucky in that whatever value is being chosen happens to look like real data?

**Comment by kernigh** [comment]
OpenBSD's junk is 0xd0 in malloc() and 0xdf in free(). The junk seems to come from the call to oldline(lnp) in cs_elim.c:remove_lines(), so one might change the junk by modifying that code. `oldline(lnp); lnp->l_instr = 0xdf` might mimic OpenBSD's behavior in Linux.

The value 0xdf = 223 might not look like real data, but it might break the loop in cs_profit.c:okay_lines().

```
	for (lnp = ocp->oc_lfirst; lnp != (line_p) 0; lnp = next) {
		next = lnp != ocp->oc_llast ? lnp->l_next : (line_p) 0;

		if (INSTR(lnp) < sp_fmnem || INSTR(lnp) > sp_lmnem)
			return FALSE;
			...
```

So INSTR(lnp) is the junk 223. I think that 223 isn't an EM mnemonic, so the loop returns FALSE. (The loop assumes that 223 is an EM pseudo. I think that 223 also isn't a pseudo, but the loop doesn't check that.) Because okay_lines() returned FALSE, we don't eliminate the lines, so we don't make the double free.

The default branch has an existing bug where CS reads lines after freeing them. The next input, `bug.c`, reproduces the bug.

```
int f(int *a, int i, int j) {
	int r = a[i];
	int s = a[j];
	a[j] = a[i];
	return r + s + a[j];
}
```

Then `ack -mlinuxppc -O3 -c.e bug.c` causes the read-after-free. I checked this by building the ack (from default 4cb4bdc), making the following change,

```
diff --git a/util/ego/share/alloc.c b/util/ego/share/alloc.c
index 2bd309b81..421ad39f3 100644
--- a/util/ego/share/alloc.c
+++ b/util/ego/share/alloc.c
@@ -116,7 +116,7 @@ line_p newline(byte optyp) {
 	line_p lnp;
 	int kind=optyp;
 
-	lnp = (line_p) newcore(lsizetab[kind]);
+	lnp = (line_p) newcore(/*lsizetab[kind]*/4096);
 	TYPE(lnp) = optyp;
 	return(lnp);
 }
```

rebuilding only util/ego+pkg, then running `MALLOC_OPTIONS=S ack -mlinuxppc -O3 -c.e bug.c`. My page size is 4096 bytes, so this wastes memory by allocating one page for each line, but then OpenBSD's MALLOC_OPTIONS=S unmaps the page when it frees the line. This makes the read after free into a segfault.

The job of CS is to eliminate common expressions. If a procedure does `x * y * z` twice, and the values are the same, then CS changes the first `x * y * z` to `tmp = x * y * z` and the second `x * y * z` to `tmp`. When CS eliminates the second `x * y * z`, it frees the EM lines. CS must process `x * y * z` before `x * y`. Suppose that CS would do `x * y` first. It would change the second `x * y * z` to `tmp * z` and free the lines for `x * y`. Then it would do `x * y * z` and free the lines for `x * y * z`. This would be a double free, because the lines for `x * y` would be freed twice. To prevent this problem, CS does expressions from last to first; `x * y * z` comes after `x * y` in the EM code. When CS eliminates `x * y * z`, it checks that `x * y * z` contains `x * y`, and forgets this occurrence of `x * y`, so it prevents the double free.

Now I go back to bug.c, which has

```
int f(int *a, int i, int j) {
	int r = a[i];
	int s = a[j];
	a[j] = a[i];
	return r + s + a[j];
}
```

In C, `a[i]` is the same as `*(a + i)`. EM uses ADS to compute `a + i` and LOI to load `*(a + i)`. The code has multiple occurrences of `a + i`, `*(a + i)`, and `a + j` in the code. The first `a + j` is after the first `*(a + i)` in the code, so CS processes `a + j` before `*(a + i)`.

The assignment `a[j] = a[i]` causes the last `a[j]` to have the same value as `a[i]`. CS tracks this, so the last `a[j]` becomes an occurrence of `*(a + i)`. This occurrence still contains an occurrence `a + j`, because the EM code says `*(a + j)`, though the value is `*(a + i)`.

I said that CS does `a + j` before `*(a + i)`. So CS eliminates the `a + j` in the last `*(a + i)`, and checks if this `a + j` contains other expressions, but doesn't check if other expressions contain this `a + j`. CS frees the EM lines for `a + j`. Then CS does `*(a + i)`, but the last occurrence of `*(a + i)` contains lines that have been freed, so CS makes a read after free.

The assignment `a[j] = a[i]` causes the confusion. The last `*(a + i)` contains `a + j`, but the first `*(a + i)` doesn't. If the first `*(a + i)` had contained `a + j`, then the first `a + j` would come before the first `*(a + i)`, so CS would do `*(a + i)` before `a + j`, so it would check if the last `*(a + i)` contained `a + j`, so it would prevent the read before free.

I left out some important details about `struct avail` and `struct occur`. I also don't know why the read after free almost never becomes a double free.

**Comment by kernigh** [comment]
I added a commit 85fcbde that checks and fixes a pointer to the memory being freed. This passes Travis.

**Comment by davidgiven** [comment]
LGTM. Thank you very much.

**Pull request merged**
